# 环境配置 test测试 dev开发 pro 生产环境
spring:
  datasource:
    #基本属性
    #driverClassName: com.mysql.jdbc.Driver
    # mysql-connector-java 6.0  （driver-class-name为com.mysql.cj.jdbc.Driver,并且需要设置serverTimezone，useSSL=false 禁用禁用SSL连接）
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/company?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    ## 下面为连接池的补充设置，应用到上面所有数据源中
    #配置初始化大小/最小/最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  # redis配置（参考：https://www.jianshu.com/p/ad2ac7412b3c）
  redis:
    ## redis 数据库索引 （默认0）
    database: 0
    ## Redis服务器地址  #哨兵模式下不用配置
    host: 101.132.106.164
    ## Redis服务器连接端口 # 哨兵模式下不用配置
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: lin1259191025
    ## 连接超时时间（毫秒） 此处不能带单位
    timeout: 10000
    # 启用SSL支持
    ssl: false
    ## lettuce 客户端
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
    ##jedis客户端
    jedis:
      pool:
        # 最大连接数 默认8
        max-active: 1000
        # 最大空闲连接 默认8
        max-idle: 10
        # 默认-1 最大连接阻塞等待时间（毫秒） 此处不能带单位 (负数表示没限制)
        max-wait: 5000
        # 最小空闲连接 默认0
        min-idle: 5
    #哨兵模式
    sentinel:
      #哨兵模式下，逗号分隔的键值对（主机：端口）形式的服务器列表
      nodes: 192.168.2.110:26379,192.168.2.110:26380,192.168.2.110:26381
      #哨兵模式下，Redis主服务器地址
      master: mymaster
    #群集模式配置
    cluster:
      #逗号分隔的键值对（主机：端口）形式的服务器列表
      nodes:
      #集群模式下，集群最大转发的数量
      max-redirects:
